### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Apelsinka223** [Sanchos01/MarsRovers#1]
https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L26-L29
ошибки лучше оборачивать в `{:error, _}`

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L18-L18
лучше проверку длины выписать в отдельную функцию, которая будет возвращать например `:ok`/`true` или `{:error, :wrong_format_file}`

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L34-L34
тут больше подойдет ` [x, y] <- head, `

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L13-L22
~~можно по дефолту сделать `opts \\ [stop_on_blocked: false]` и убрать присваивание~~

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L28-L36
лучше заменить на if

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L39-L51
когда много параметров лучше добавить `@spec` и не повторять названия после `_`, иначе тяжело читать. Ну и в длинной строке `do:` надо перенести
`(new_x == s_x and new_y == s_y) or (new_x == new_s_x and new_y == new_s_y)`  лучше вынести в отдельную функцию проверки

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/state.ex#L17-L24
обе проверки выделить в отдельные функции, которые будут возвращать соответствующие ошибки(можно будет обойтись без else)

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/state.ex#L4-L4
круто, не знала что так можно 👍 

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/state.ex#L34-L41
тут по идее можно было в одной функции все задать

**Comment by Sanchos01** [comment]
Итак по пунктам:
https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L26-L29
удалил `false -> :wrong_format_file` за ненадобностью

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L18-L18
завернул в отдельную функцию, которая возвращает :ok / :wrong_format_file . Заворачивать ошибки в кортеж не вижу смысла, потому что при нормальном исходе возвращается строка, в случае ошибок - атом. Думаю элементарной проверки на тип хватит

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/file_parse.ex#L34-L34
исправил

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L13-L22
маленькая правка на:
https://github.com/Sanchos01/MarsRovers/blob/e9e3dde09c9e609e2cdd6277fa0ff52336eef966/lib/mars_rovers.ex#L17

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L28-L36
исправил `case` на `if` (хотя глубокого смысла в этом нету)

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/mars_rovers.ex#L39-L51
добавил определение функции:
https://github.com/Sanchos01/MarsRovers/blob/e9e3dde09c9e609e2cdd6277fa0ff52336eef966/lib/mars_rovers.ex#L39
остальное в данном пункте дело вкуса

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/state.ex#L17-L24
переделал, теперь-то покрасивше выглядит. И без лишних кортежей
https://github.com/Sanchos01/MarsRovers/blob/da25f95114b71ff4b96bbc0e323b5b0bd0cfdb3d/lib/state.ex#L16-L31

https://github.com/Sanchos01/MarsRovers/blob/a1de680222d6e7998f6bd77f4f7e3dbc68b02381/lib/state.ex#L34-L41
Если создавать в одной функции, придется каждую итерацию пересоздавать структуру. Сомнительная затея
